# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  livraria:
    image: livraria
    build:
      context: .
      dockerfile: livraria/Dockerfile
    ports:
      - 5028:5028
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
