# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  livraria:
    image: livraria
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5028:5028
   

  sqlbase:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Local@1234
      - ACCEPT_EULA=Y

    volumes:
      - ~\Volumes\Mssql:/var/opt/mssql/data
    ports:
      - "1433:1433"
